packages:
  - apps/*
  - packages/*
  - prisma
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/engines'
  - prisma
  - esbuild
  - sharp
  - '@tailwindcss/oxide'
  - argon2
ignoredBuiltDependencies:
  - '@scarf/scarf'
